from __future__ import annotations

from typing import Any, Dict, List

AWARDS_2025: List[Dict[str, Any]] = [
    {
        "id": "mais-completo",
        "title": "Quem é o jogador mais completo?",
        "tagline": "O pacote inteiro para qualquer missão.",
        "category_type": "positive",
        "votes": {
            "Júlio Picôto": 9,
            "Lucas Cuervo": 7,
            "J. Victor Adão": 5,
            "Eduardo Costa": 3,
            "Vitor Cuervo": 1,
            "Leandro Costa": 1,
            "Diogo Bodas": 1,
            "Tadeu Calleri": 1,
            "Lucas Torres": 1,
            "Gabriel Ferreira": 1,
            "Thiago Makasevicius": 1,
        },
    },
    {
        "id": "melhor-ataque",
        "title": "Quem tem o melhor ataque?",
        "tagline": "Os destaques quando a bola pede potência.",
        "category_type": "positive",
        "votes": {
            "Júlio Picôto": 8,
            "Vitor Cuervo": 6,
            "Tadeu Calleri": 4,
            "Diogo Bodas": 3,
            "J. Victor Adão": 3,
            "Pedro Vilela": 2,
            "Eduardo Costa": 2,
            "Fernando Kling": 2,
            "Leandro Costa": 1,
            "Diego Makasevicius": 1,
            "Gabriel Ferreira": 1,
            "Lucas Cuervo": 1,
            "Paulo Calçada": 1,
        },
    },
    {
        "id": "melhor-defesa",
        "title": "Quem apresenta a melhor defesa?",
        "tagline": "Quem fecha a quadra e deixa tudo jogável.",
        "category_type": "positive",
        "votes": {
            "Júlio Picôto": 9,
            "Lucas Cuervo": 6,
            "Lucas Torres": 5,
            "Pedro Vilela": 4,
            "Eduardo Costa": 3,
            "Tadeu Calleri": 2,
            "Marcelo Engelke": 1,
            "Gabriel Ferreira": 1,
            "Hugo Moura": 1,
            "Paulo Calçada": 1,
            "Diogo Bodas": 1,
            "Leandro Costa": 1,
            "J. Victor Adão": 1,
        },
    },
    {
        "id": "melhor-levantada",
        "title": "Quem tem a melhor levantada?",
        "tagline": "Precisão cirúrgica para deixar o ataque livre.",
        "category_type": "positive",
        "votes": {
            "Diego Makasevicius": 5,
            "Lucas Cuervo": 5,
            "Pedro Vilela": 5,
            "Diogo Bodas": 4,
            "Bruno Rubi": 4,
            "Gabriel Ferreira": 4,
            "Paulo Calçada": 2,
            "J. Victor Adão": 2,
            "Marcelo Engelke": 1,
            "Lucas Torres": 1,
            "Fernando Kling": 1,
            "Eduardo Costa": 1,
            "Hugo Moura": 1,
            "Júlio Picôto": 1,
            "Leandro Costa": 1,
        },
    },
    {
        "id": "melhor-leitura",
        "title": "Quem tem a melhor leitura de jogo?",
        "tagline": "Visão de jogo que antecipa todas as jogadas.",
        "category_type": "positive",
        "votes": {
            "Lucas Cuervo": 9,
            "Júlio Picôto": 7,
            "Lucas Torres": 6,
            "Pedro Vilela": 4,
            "Fernando Kling": 3,
            "Paulo Calçada": 2,
            "Tadeu Calleri": 2,
            "J. Victor Adão": 2,
            "Thomaz Santos": 1,
            "Hugo Moura": 1,
        },
    },
    {
        "id": "cobertura-de-quadra",
        "title": "Quem faz a melhor cobertura de quadra?",
        "tagline": "Quem aparece em todo canto para salvar o ponto.",
        "category_type": "positive",
        "votes": {
            "Júlio Picôto": 13,
            "Lucas Cuervo": 3,
            "Diogo Bodas": 3,
            "Lucas Torres": 3,
            "Eduardo Costa": 3,
            "Tadeu Calleri": 3,
            "Pedro Vilela": 2,
            "Leandro Costa": 1,
            "Heitor Ribeiro": 1,
            "Diego Makasevicius": 1,
            "Marcelo Engelke": 1,
        },
    },
    {
        "id": "mais-incansavel",
        "title": "Quem é o mais incansável em quadra?",
        "tagline": "Energia que não acaba nunca.",
        "category_type": "positive",
        "votes": {
            "Júlio Picôto": 9,
            "Diogo Bodas": 4,
            "Tadeu Calleri": 3,
            "Eduardo Costa": 3,
            "Gabriel Ferreira": 3,
            "Lucas Cuervo": 2,
            "Pedro Vilela": 2,
            "Marcelo Engelke": 2,
            "J. Victor Adão": 1,
            "Vitor Cuervo": 1,
            "Lucas Torres": 1,
            "Leandro Costa": 1,
            "Bruno Rubi": 1,
        },
    },
    {
        "id": "ombro-magico",
        "title": "Quem é o dono do “ombro mágico”?",
        "tagline": "Os passes milagrosos da galera.",
        "category_type": "positive",
        "votes": {
            "Diego Makasevicius": 11,
            "Bruno Rubi": 4,
            "Gabriel Ferreira": 4,
            "Lucas Cuervo": 3,
            "Hugo Moura": 3,
            "Fernando Kling": 2,
            "J. Victor Adão": 2,
            "Vitor Cuervo": 1,
            "Pedro Vilela": 1,
            "Lucas Torres": 1,
            "Tadeu Calleri": 1,
            "Marcelo Engelke": 1,
        },
    },
    {
        "id": "chapa-de-ouro",
        "title": "Quem é o chapa de ouro do grupo?",
        "tagline": "O favorito para dividir a quadra em qualquer situação.",
        "category_type": "positive",
        "votes": {
            "Paulo Calçada": 14,
            "Lucas Cuervo": 9,
            "Vitor Cuervo": 3,
            "Tadeu Calleri": 2,
            "Bruno Rubi": 1,
            "Pedro Vilela": 1,
            "Júlio Picôto": 1,
            "Diego Makasevicius": 1,
            "Fernando Kling": 1,
        },
    },
    {
        "id": "peitada-na-lua",
        "title": "Quem manda a peitada na lua?",
        "tagline": "Quem resolve no grito e no peito.",
        "category_type": "positive",
        "votes": {
            "Diogo Bodas": 9,
            "J. Victor Adão": 7,
            "Eduardo Costa": 5,
            "Pedro Vilela": 5,
            "Júlio Picôto": 2,
            "Gabriel Ferreira": 1,
            "Bruno Rubi": 1,
        },
    },
    {
        "id": "pior-ataque",
        "title": "Quem tem o pior ataque?",
        "tagline": "Quando o ponto pede paciência extra.",
        "category_type": "negative",
        "votes": {
            "Bruno Rubi": 11,
            "Thiago Makasevicius": 7,
            "Marcelo Engelke": 5,
            "Lucas Torres": 3,
            "Hugo Moura": 2,
            "André Scherer": 2,
            "Gabriel Ferreira": 1,
            "Thales Duarte": 1,
            "Lucas Cuervo": 1,
        },
    },
    {
        "id": "pior-levantada",
        "title": "Quem tem a pior levantada?",
        "tagline": "Quem dá emoção demais na armação.",
        "category_type": "negative",
        "votes": {
            "Thiago Makasevicius": 7,
            "André Scherer": 4,
            "Vitor Cuervo": 4,
            "Hugo Moura": 3,
            "Bruno Rubi": 3,
            "Eduardo Costa": 2,
            "Gabriel Ferreira": 2,
            "Lucas Cuervo": 2,
            "Marcelo Engelke": 2,
            "Júlio Picôto": 1,
            "Lucas Torres": 1,
            "Heitor Ribeiro": 1,
            "Fernando Kling": 1,
            "Tadeu Calleri": 1,
        },
    },
    {
        "id": "psicologico-mais-fraco",
        "title": "Quem tem o psicológico mais fraco?",
        "tagline": "Quando a confiança oscila demais.",
        "category_type": "negative",
        "votes": {
            "Lucas Torres": 9,
            "Fernando Kling": 7,
            "Pedro Vilela": 5,
            "Bruno Rubi": 5,
            "Tadeu Calleri": 3,
            "Hugo Moura": 3,
            "Eduardo Costa": 2,
            "Gabriel Ferreira": 1,
            "Thiago Makasevicius": 1,
        },
    },
    {
        "id": "talento-desperdicado",
        "title": "Quem é o maior talento desperdiçado?",
        "tagline": "O potencial que ainda não virou realidade.",
        "category_type": "negative",
        "votes": {
            "Pedro Vilela": 7,
            "Vitor Cuervo": 3,
            "Júlio Picôto": 2,
            "Diogo Bodas": 2,
            "J. Victor Adão": 2,
            "Lucas Torres": 2,
            "André Scherer": 2,
            "Tadeu Calleri": 2,
            "Paulo Calçada": 1,
            "Leandro Costa": 1,
            "Gabriel Ferreira": 1,
            "Marcelo Engelke": 1,
            "Lucas Cuervo": 1,
            "Bruno Rubi": 1,
        },
    },
    {
        "id": "desconexo-realidade",
        "title": "Quem é o mais desconexo com a realidade (o que acha que joga vs. o que realmente joga)?",
        "tagline": "",
        "category_type": "negative",
        "votes": {
            "Bruno Rubi": 10,
            "Fernando Kling": 8,
            "Hugo Moura": 4,
            "Eduardo Costa": 3,
            "Vitor Cuervo": 3,
            "Lucas Torres": 2,
            "Thiago Makasevicius": 2,
            "Thales Duarte": 1,
        },
    },
    {
        "id": "ladrao-de-pontos",
        "title": "Quem é o mais ladrão de pontos?",
        "tagline": "Sempre por perto para pegar a última bola.",
        "category_type": "negative",
        "votes": {
            "Bruno Rubi": 11,
            "Lucas Torres": 9,
            "Diego Makasevicius": 5,
            "Eduardo Costa": 3,
            "Hugo Moura": 1,
            "Júlio Picôto": 1,
            "Fernando Kling": 1,
            "Pedro Vilela": 1,
            "Vitor Cuervo": 1,
        },
    },
    {
        "id": "mais-maluco",
        "title": "Quem é o mais maluco em quadra?",
        "tagline": "O imprevisível que sempre surpreende.",
        "category_type": "negative",
        "votes": {
            "Bruno Rubi": 10,
            "Vitor Cuervo": 7,
            "Fernando Kling": 4,
            "Pedro Vilela": 4,
            "Lucas Torres": 3,
            "Eduardo Costa": 2,
            "Thiago Makasevicius": 1,
            "Diego Makasevicius": 1,
        },
    },
    {
        "id": "mais-cansado",
        "title": "Quem é o mais cansado?",
        "tagline": "A galera que precisa de um intervalo a mais.",
        "category_type": "negative",
        "votes": {
            "Pedro Vilela": 8,
            "Diego Makasevicius": 7,
            "Lucas Torres": 4,
            "Thiago Makasevicius": 3,
            "André Scherer": 3,
            "Vitor Cuervo": 2,
            "Thales Duarte": 1,
            "Marcelo Engelke": 1,
            "Hugo Moura": 1,
            "Lucas Cuervo": 1,
        },
    },
    {
        "id": "mais-chorao",
        "title": "Quem é o mais chorão?",
        "tagline": "Quando a reclamação vem antes do ponto.",
        "category_type": "negative",
        "votes": {
            "Eduardo Costa": 8,
            "Bruno Rubi": 7,
            "Lucas Torres": 6,
            "Fernando Kling": 5,
            "Hugo Moura": 4,
            "Júlio Picôto": 1,
            "Vitor Cuervo": 1,
            "Lucas Cuervo": 1,
        },
    },
    {
        "id": "noe-do-grupo",
        "title": "Quem é o Noé do grupo (carrega qualquer animal)?",
        "tagline": "O escolhido para carregar até o piano.",
        "category_type": "positive",
        "votes": {
            "Júlio Picôto": 9,
            "Lucas Cuervo": 8,
            "J. Victor Adão": 4,
            "Pedro Vilela": 3,
            "Heitor Ribeiro": 1,
            "Diogo Bodas": 1,
            "Fernando Kling": 1,
            "Leandro Costa": 1,
            "Paulo Calçada": 1,
            "Thomaz Santos": 1,
            "Tadeu Calleri": 1,
            "Lucas Torres": 1,
            "Vitor Cuervo": 1,
        },
    },
]
